wandb_version: 1

architecture:
  desc: null
  value: Swin-BirefNet
dataset:
  desc: null
  value: CVC-ClinicDB
NUM_CLASSES:
  desc: null
  value: 1
PRETRAINED:
  desc: null
  value: true
FREEZE_BACKBONE:
  desc: null
  value: true
DROPOUT:
  desc: null
  value: 0.1
NUM_EPOCHS:
  desc: null
  value: 100
LEARNING_RATE:
  desc: null
  value: 0.0002
WEIGHT_DECAY:
  desc: null
  value: 0.0001
DEVICE:
  desc: null
  value: cpu
TRAIN_SIZE:
  desc: null
  value: 0.7
VAL_SIZE:
  desc: null
  value: 0.15
TEST_SIZE:
  desc: null
  value: 0.15
SEED:
  desc: null
  value: 42
BCE_WEIGHT:
  desc: null
  value: 1.0
DICE_WEIGHT:
  desc: null
  value: 1.0
DEEP_SUPERVISION_WEIGHT:
  desc: null
  value: 0.4
AUX_WEIGHT:
  desc: null
  value: 0.2
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742750730.860834
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 80
      3:
      - 16
      - 23
      4: 3.10.11
      5: 0.16.3
      6: 4.36.2
      8:
      - 4
      - 5
      13: darwin-arm64
