wandb_version: 1

architecture:
  desc: null
  value: DeepLabV3+
dataset:
  desc: null
  value: CVC-ClinicDB
ENCODER:
  desc: null
  value: resnet50
ENCODER_WEIGHTS:
  desc: null
  value: imagenet
NUM_CLASSES:
  desc: null
  value: 1
ACTIVATION:
  desc: null
  value: sigmoid
NUM_EPOCHS:
  desc: null
  value: 15
LEARNING_RATE:
  desc: null
  value: 8.0e-05
WEIGHT_DECAY:
  desc: null
  value: 0.0001
DEVICE:
  desc: null
  value: cpu
TRAIN_SIZE:
  desc: null
  value: 0.9
VAL_SIZE:
  desc: null
  value: 0.1
TEST_SIZE:
  desc: null
  value: 0.0
SEED:
  desc: null
  value: 42
BATCH_SIZE:
  desc: null
  value: 16
NUM_WORKERS:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742826883.39981
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      3:
      - 16
      - 23
      4: 3.10.11
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
